apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: production-daily
spec:
  schedule: '0 2 * * *'
  ConcurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: dailycron
        spec:
          containers:
            -
              name: batch
              image: 'docker-registry.default.svc:5000/srs/production'
              envFrom:
              - configMapRef:
                  name: production
              command:
                - python3
                - manage.py
                - dailyjob
          restartPolicy: OnFailure
