# Generated by Django 2.1.5 on 2019-02-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0002_auto_20190122_1609'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='PINN_CUSTOM"."UM_OSC_VALID_ROLES',
        ),
    ]
