# Generated by Django 2.1.5 on 2019-02-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0003_auto_20190205_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descr', models.CharField(max_length=200)),
            ],
        ),
    ]
