# Generated by Django 2.2 on 2020-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
