# Generated by Django 3.2.4 on 2022-09-14 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserDeptV',
            fields=[
                ('codename', models.CharField(blank=True, max_length=20)),
                ('dept', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_dept_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LDAPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_seq_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('role', models.CharField(max_length=30, unique=True)),
                ('role_description', models.CharField(max_length=1000)),
                ('grantable_by_dept', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('inactivation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Inactivated')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('created_by', models.CharField(default='Not implemented', max_length=150)),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Last Date Updated')),
                ('last_updated_by', models.CharField(default='Not implemented', max_length=150)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'auth_role',
                'permissions': [('can_administer_access_all', 'Can Modify All Access Privileges'), ('can_administer_access', 'Can Modify Access Privileges (except proxy)'), ('can_order', 'All ordering functions'), ('can_report', 'Can run reports'), ('can_impersonate', 'Can Impersonate'), ('can_move_voip', 'Can Submit VOIP Location Changes'), ('can_report_all', 'Can run all reports without restrictions')],
            },
        ),
        migrations.CreateModel(
            name='LDAPGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('ldap_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Grantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_seq_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('granted_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oscauth.role')),
                ('grantor_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
            options={
                'db_table': 'auth_grantor',
                'unique_together': {('grantor_role', 'granted_role')},
            },
        ),
        migrations.CreateModel(
            name='AuthUserDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(blank=True, max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_dept',
                'unique_together': {('user', 'group', 'dept')},
            },
        ),
    ]
