# Generated by Django 4.1.7 on 2024-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSecurityV',
            fields=[
                ('username', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('srs_role', models.CharField(blank=True, max_length=150)),
                ('deptid', models.CharField(blank=True, max_length=10)),
                ('dept_effdt', models.DateField()),
                ('dept_eff_status', models.CharField(blank=True, max_length=1)),
                ('dept_descr', models.CharField(blank=True, max_length=30)),
                ('emplid', models.CharField(blank=True, max_length=11)),
                ('dept_grp', models.CharField(blank=True, max_length=20)),
                ('dept_grp_descr', models.CharField(blank=True, max_length=30)),
                ('dept_grp_vp_area', models.CharField(blank=True, max_length=20)),
                ('dept_grp_vp_area_descr', models.CharField(blank=True, max_length=30)),
                ('dept_grp_campus', models.CharField(blank=True, max_length=20)),
                ('dept_grp_campus_descr', models.CharField(blank=True, max_length=30)),
                ('dept_bud_seq', models.CharField(blank=True, max_length=20)),
                ('dept_bud_seq_descr', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'department_security_v',
                'managed': False,
            },
        ),
    ]
