# Generated by Django 2.1.5 on 2019-02-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0002_roleprivilege_roleprivrestriction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roleprivilege',
            table='role_privilege',
        ),
        migrations.AlterModelTable(
            name='roleprivrestriction',
            table='role_priv_restriction',
        ),
    ]
