# Generated by Django 2.1.5 on 2019-02-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0003_auto_20190220_1027'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roleprivilege',
            table='oscauth_role_privilege',
        ),
        migrations.AlterModelTable(
            name='roleprivrestriction',
            table='oscauth_role_priv_restriction',
        ),
    ]
