# Generated by Django 2.1.5 on 2019-03-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oscauth', '0006_auto_20190301_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(blank=True, max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_dept',
            },
        ),
        migrations.RemoveField(
            model_name='roleprivilege',
            name='privilege',
        ),
        migrations.RemoveField(
            model_name='roleprivilege',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roleprivrestriction',
            name='privilege',
        ),
        migrations.RemoveField(
            model_name='roleprivrestriction',
            name='restriction',
        ),
        migrations.RemoveField(
            model_name='roleprivrestriction',
            name='role',
        ),
        migrations.AlterModelTable(
            name='role',
            table='auth_role',
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
        migrations.DeleteModel(
            name='Restriction',
        ),
        migrations.DeleteModel(
            name='RolePrivilege',
        ),
        migrations.DeleteModel(
            name='RolePrivRestriction',
        ),
    ]
