# Generated by Django 2.1.5 on 2019-03-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0010_auto_20190307_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='user',
            new_name='group',
        ),
    ]
