# Generated by Django 2.1.5 on 2019-03-20 19:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oscauth', '0011_auto_20190307_1357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authuserdept',
            unique_together={('user', 'group', 'dept')},
        ),
    ]
