# Generated by Django 2.2 on 2019-04-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0012_auto_20190320_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.CharField(default='Not implemented', max_length=150),
        ),
        migrations.AlterField(
            model_name='role',
            name='last_updated_by',
            field=models.CharField(default='Not implemented', max_length=150),
        ),
    ]
