# Generated by Django 2.2 on 2019-04-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('oscauth', '0013_auto_20190403_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_seq_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('granted_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oscauth.Role')),
                ('grantor_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
            ],
            options={
                'db_table': 'auth_grantor',
            },
        ),
    ]
