# Generated by Django 2.2 on 2019-05-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0015_auto_20190508_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_order', 'All ordering functions'), ('can_proxy', 'Can Proxy'), ('can_report', 'Can run reports')]},
        ),
    ]
