# Generated by Django 2.2 on 2019-05-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0016_auto_20190529_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_order', 'All ordering functions'), ('can_proxy', 'Can Proxy'), ('can_report', 'Can run reports'), ('can_impersonate', 'Can Impersonate')]},
        ),
    ]
