# Generated by Django 2.2 on 2019-06-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0017_auto_20190529_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserDeptV',
            fields=[
                ('codename', models.CharField(blank=True, max_length=20)),
                ('dept', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_dept_v',
                'managed': False,
            },
        ),
    ]
