# Generated by Django 2.2 on 2019-06-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0018_authuserdeptv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_administer_access_all', 'Can Modify All Access Privileges'), ('can_administer_access', 'Can Modify Access Privileges (except proxy)'), ('can_order', 'All ordering functions'), ('can_report', 'Can run reports'), ('can_impersonate', 'Can Impersonate')]},
        ),
    ]
