# Generated by Django 2.2 on 2019-08-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0019_auto_20190617_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_administer_access_all', 'Can Modify All Access Privileges'), ('can_administer_access', 'Can Modify Access Privileges (except proxy)'), ('can_order', 'All ordering functions'), ('can_report', 'Can run reports'), ('can_impersonate', 'Can Impersonate'), ('can_move_voip', 'Can Submit VOIP Location Changes'), ('can_report_all', 'Can run all reports without restrictions')]},
        ),
    ]
