# Generated by Django 2.2 on 2020-06-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0020_auto_20190801_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LDAPGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('ldap_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oscauth.LDAPGroup')),
            ],
        ),
    ]
