# Generated by Django 2.2 on 2020-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0021_ldapgroup_ldapgroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
