# Generated by Django 3.2.4 on 2021-12-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0022_ldapgroup_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapgroup',
            options={'ordering': ['name']},
        ),
    ]
