# Generated by Django 4.1.2 on 2022-11-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('oscauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1)),
                ('billing_contact', models.CharField(max_length=80)),
                ('shortcode', models.CharField(max_length=6)),
                ('account_id', models.CharField(default='TBD', max_length=30, verbose_name='Billing ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup')),
            ],
            options={
                'verbose_name': 'Google Cloud Platform Account',
            },
        ),
        migrations.CreateModel(
            name='GCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1)),
                ('requestor', models.CharField(max_length=8)),
                ('security_contact', models.CharField(max_length=80)),
                ('created_date', models.DateField(auto_now=True)),
                ('project_id', models.CharField(max_length=40)),
                ('gcp_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.gcpaccount')),
                ('non_regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'NON_REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_nonreg_related', to='project.choice')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='oscauth.ldapgroup')),
                ('regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_reg_related', to='project.choice')),
            ],
            options={
                'verbose_name': 'Google Cloud Platform Project',
            },
        ),
        migrations.CreateModel(
            name='Azure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1)),
                ('requestor', models.CharField(max_length=8)),
                ('security_contact', models.CharField(max_length=80)),
                ('billing_contact', models.CharField(max_length=80)),
                ('shortcode', models.CharField(max_length=6)),
                ('created_date', models.DateField(auto_now=True)),
                ('account_id', models.CharField(default='TBD', max_length=40, verbose_name='Subscription ID')),
                ('name', models.CharField(default='TBD', max_length=40)),
                ('non_regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'NON_REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_nonreg_related', to='project.choice')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup')),
                ('regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_reg_related', to='project.choice')),
                ('vpn_tier', models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'VPN_TIER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.choice')),
            ],
            options={
                'verbose_name': 'Azure Subscription',
            },
        ),
        migrations.CreateModel(
            name='AWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='TBD', max_length=30)),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1)),
                ('requestor', models.CharField(max_length=8)),
                ('security_contact', models.CharField(max_length=80)),
                ('billing_contact', models.CharField(max_length=80)),
                ('shortcode', models.CharField(max_length=6)),
                ('created_date', models.DateField(auto_now=True)),
                ('data_classification', models.CharField(blank=True, max_length=10, null=True)),
                ('egress_waiver', models.BooleanField()),
                ('non_regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'NON_REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_nonreg_related', to='project.choice')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup')),
                ('regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_reg_related', to='project.choice')),
                ('version', models.ForeignKey(default=132, limit_choices_to={'parent__code': 'AWS_VERSION'}, on_delete=django.db.models.deletion.CASCADE, to='project.choice')),
            ],
            options={
                'verbose_name': 'Amazon Web Services Account',
            },
        ),
    ]
