# Generated by Django 3.2.13 on 2022-12-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualDesktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=6)),
                ('pool_name', models.CharField(max_length=100)),
                ('gpu', models.BooleanField()),
                ('memory', models.CharField(max_length=4)),
                ('cpu', models.CharField(max_length=4)),
                ('storage', models.CharField(max_length=8)),
                ('individual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_computers', models.CharField(max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_group', models.CharField(max_length=100)),
            ],
        ),
    ]
