# Generated by Django 3.2.4 on 2022-01-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aws',
            options={'verbose_name_plural': 'AWS Accounts'},
        ),
        migrations.AlterModelOptions(
            name='azure',
            options={'verbose_name_plural': 'Azure Accounts'},
        ),
        migrations.AlterModelOptions(
            name='gcp',
            options={'verbose_name_plural': 'GCP Accounts'},
        ),
        migrations.AddField(
            model_name='gcpproject',
            name='project_id',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
