# Generated by Django 3.2.4 on 2022-02-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azure',
            name='account_id',
            field=models.CharField(max_length=40, verbose_name='Subscription ID'),
        ),
    ]
