# Generated by Django 4.1.7 on 2023-05-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'managed': False},
        ),
    ]
