# Generated by Django 4.1.7 on 2023-06-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0001_initial'),
        ('project', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='CloudImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1)),
                ('requestor', models.CharField(max_length=8)),
                ('security_contact', models.CharField(max_length=80)),
                ('billing_contact', models.CharField(max_length=80)),
                ('shortcode', models.CharField(max_length=6)),
                ('created_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('cpu', models.CharField(max_length=4)),
                ('cpu_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memory', models.CharField(max_length=4)),
                ('memory_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('storage', models.CharField(max_length=8)),
                ('storage_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gpu', models.BooleanField()),
                ('gpu_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account_id', models.CharField(default='TBD', max_length=30, verbose_name='Image Name')),
                ('non_regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'NON_REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_nonreg_related', to='project.choice')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup')),
                ('regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_reg_related', to='project.choice')),
            ],
            options={
                'verbose_name': 'MiServer Cloud Desktop Image',
                'db_table': 'srs_services_clouddimagetest',
            },
        ),
        migrations.CreateModel(
            name='CloudDesktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1)),
                ('requestor', models.CharField(max_length=8)),
                ('security_contact', models.CharField(max_length=80)),
                ('billing_contact', models.CharField(max_length=80)),
                ('shortcode', models.CharField(max_length=6)),
                ('created_date', models.DateField(auto_now=True)),
                ('account_id', models.CharField(default='TBD', max_length=30, verbose_name='Pool Name')),
                ('pool_maximum', models.IntegerField()),
                ('pool_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ad_access_groups', models.CharField(max_length=100)),
                ('sla', models.BooleanField()),
                ('persistent_vm', models.BooleanField(default=False)),
                ('non_regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'NON_REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_nonreg_related', to='project.choice')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup')),
                ('regulated_data', models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'REGULATED_SENSITIVE_DATA'}, related_name='%(class)s_reg_related', to='project.choice')),
            ],
            options={
                'verbose_name': 'MiServer Cloud Desktop Pool',
                'db_table': 'srs_services_clouddesktoptest',
            },
        ),
    ]
