# Generated by Django 4.1.7 on 2023-05-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'managed': False},
        ),
    ]
# Generated by Django 4.1.7 on 2023-05-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'managed': False},
        ),
    ]
