# Generated by Django 3.2.13 on 2023-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_virtualdesktop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, unique=True)),
                ('gpu', models.BooleanField()),
                ('memory', models.CharField(max_length=4)),
                ('cpu', models.CharField(max_length=4)),
                ('storage', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=6)),
                ('pool_name', models.CharField(max_length=100, unique=True)),
                ('individual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_computers', models.CharField(max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_group', models.CharField(max_length=100)),
                ('base_image', models.ManyToManyField(to='services.BaseImage')),
            ],
        ),
        migrations.DeleteModel(
            name='VirtualDesktop',
        ),
    ]
