# Generated by Django 4.1.7 on 2023-08-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0001_initial'),
        ('services', '0002_alter_container_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1)),
                ('created_date', models.DateField(auto_now=True)),
                ('name', models.CharField(default='TBD', max_length=30, verbose_name='Image Name')),
                ('cpu', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('gpu', models.BooleanField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup')),
            ],
            options={
                'verbose_name': 'MiDesktop Image',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1)),
                ('created_date', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('size', models.CharField(blank=True, max_length=80)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup')),
            ],
            options={
                'verbose_name': 'MiDesktop Network',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1)),
                ('created_date', models.DateField(auto_now=True)),
                ('shortcode', models.CharField(max_length=6)),
                ('name', models.CharField(default='TBD', max_length=30, verbose_name='Pool Name')),
                ('type', models.CharField(default='instant-clone', max_length=30)),
                ('quantity', models.IntegerField()),
                ('shared_network', models.BooleanField(default=True)),
                ('images', models.ManyToManyField(to='services.image')),
                ('network', models.ManyToManyField(to='services.network')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup')),
            ],
            options={
                'verbose_name': 'MiDesktop Pool',
            },
        ),
        migrations.CreateModel(
            name='ImageDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='services.image')),
            ],
        ),
    ]
