# Generated by Django 4.1.7 on 2023-06-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_container_options_cloudimage_clouddesktop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudimage',
            name='gpu',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
