# Generated by Django 3.2.4 on 2022-02-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_umoscacctchangerequest_umoscauthusersapi'),
        ('services', '0002_alter_azure_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='azure',
            name='non_regulated_data',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'NON_REGULATED_SENSITIVE_DATA'}, related_name='azure_nonreg_related', to='project.Choice'),
        ),
        migrations.AddField(
            model_name='azure',
            name='regulated_data',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'REGULATED_SENSITIVE_DATA'}, related_name='azure_reg_related', to='project.Choice'),
        ),
        migrations.AddField(
            model_name='gcp',
            name='non_regulated_data',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'NON_REGULATED_SENSITIVE_DATA'}, related_name='gcp_nonreg_related', to='project.Choice'),
        ),
        migrations.AddField(
            model_name='gcp',
            name='regulated_data',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'REGULATED_SENSITIVE_DATA'}, related_name='gcp_reg_related', to='project.Choice'),
        ),
        migrations.AlterField(
            model_name='aws',
            name='account_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='aws',
            name='non_regulated_data',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'NON_REGULATED_SENSITIVE_DATA'}, related_name='aws_nonreg_related', to='project.Choice'),
        ),
        migrations.AlterField(
            model_name='aws',
            name='regulated_data',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'REGULATED_SENSITIVE_DATA'}, related_name='aws_reg_related', to='project.Choice'),
        ),
        migrations.AlterField(
            model_name='gcp',
            name='account_id',
            field=models.CharField(max_length=30),
        ),
    ]
