# Generated by Django 4.1.7 on 2023-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_cloudimage_gpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudimage',
            name='name',
        ),
        migrations.AddField(
            model_name='clouddesktop',
            name='image_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
