# Generated by Django 3.2.13 on 2023-03-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20230105_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'managed': False},
        ),
    ]
