# Generated by Django 4.1.7 on 2023-08-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_image_pool_network_imagedisk_image_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.network'),
        ),
    ]
