# Generated by Django 3.2.4 on 2022-02-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220212_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_contact', models.CharField(max_length=80)),
                ('shortcode', models.CharField(max_length=6)),
                ('account_id', models.CharField(max_length=30, verbose_name='Billing ID')),
            ],
            options={
                'verbose_name_plural': 'GCP Accounts',
            },
        ),
        migrations.AlterModelOptions(
            name='azure',
            options={'verbose_name_plural': 'Azure Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='gcp',
            options={},
        ),
        migrations.RemoveField(
            model_name='gcp',
            name='billing_contact',
        ),
        migrations.RemoveField(
            model_name='gcp',
            name='shortcode',
        ),
        migrations.AddField(
            model_name='gcp',
            name='project_id',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GCPProject',
        ),
        migrations.AddField(
            model_name='gcp',
            name='gcp_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.gcpaccount'),
            preserve_default=False,
        ),
    ]
