# Generated by Django 4.1.9 on 2023-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_image_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(default='TBD', max_length=40, verbose_name='Pool Name'),
        ),
    ]
