# Generated by Django 4.1.7 on 2023-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_cloudimage_name_clouddesktop_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouddesktop',
            name='access_internet',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='clouddesktop',
            name='mask',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='clouddesktop',
            name='protection',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='clouddesktop',
            name='technical_contact',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
