# Generated by Django 3.2.4 on 2022-02-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220212_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcp',
            name='account_id',
        ),
    ]
