# Generated by Django 4.1.7 on 2023-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_clouddesktop_access_internet_clouddesktop_mask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouddesktop',
            name='shared_network',
            field=models.BooleanField(default=True),
        ),
    ]
