# Generated by Django 4.1.9 on 2023-12-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_pool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='vlan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
