# Generated by Django 3.2.4 on 2022-02-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_gcp_account_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcp',
            options={'verbose_name_plural': 'GCP Projects'},
        ),
        migrations.AddField(
            model_name='aws',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='azure',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='gcp',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='gcpaccount',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('E', 'Ended'), ('P', 'Pending')], default='A', max_length=1),
        ),
    ]
