# Generated by Django 3.2.4 on 2022-04-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_umoscacctchangerequest_umoscauthusersapi'),
        ('services', '0006_auto_20220212_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aws',
            options={'verbose_name': 'Amazon Web Services Account'},
        ),
        migrations.AlterModelOptions(
            name='azure',
            options={'verbose_name': 'Azure Subscription'},
        ),
        migrations.AlterModelOptions(
            name='gcp',
            options={'verbose_name': 'Google Cloud Platform Project'},
        ),
        migrations.AlterModelOptions(
            name='gcpaccount',
            options={'verbose_name': 'Google Cloud Platform Account'},
        ),
        migrations.AddField(
            model_name='azure',
            name='vpn_tier',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'VPN_TIER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.choice'),
        ),
        migrations.AlterField(
            model_name='aws',
            name='account_id',
            field=models.CharField(default='TBD', max_length=30),
        ),
        migrations.AlterField(
            model_name='aws',
            name='version',
            field=models.ForeignKey(default=132, limit_choices_to={'parent__code': 'AWS_VERSION'}, on_delete=django.db.models.deletion.CASCADE, to='project.choice'),
        ),
    ]
