# Generated by Django 4.1.7 on 2023-06-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_container_options'),
        ('services', '0006_clouddesktop_shared_network'),
    ]

    operations = [
    ]
