# Generated by Django 5.0 on 2024-02-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_network_vlan_id_alter_image_name_alter_network_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='TBD', max_length=30, unique=True, verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(default='TBD', max_length=40, unique=True, verbose_name='Pool Name'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='type',
            field=models.CharField(default='instant_clone', max_length=30),
        ),
    ]
