# Generated by Django 3.2.4 on 2022-05-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0023_alter_ldapgroup_options'),
        ('services', '0007_auto_20220412_1831'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='gcpaccount',
        #    name='owner',
        #    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup'),
        #),
        migrations.AlterField(
            model_name='azure',
            name='account_id',
            field=models.CharField(default='TBD', max_length=40, verbose_name='Subscription ID'),
        ),
        migrations.AlterField(
            model_name='azure',
            name='name',
            field=models.CharField(default='TBD', max_length=40),
        ),
        migrations.AddField(
            model_name='gcp',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='oscauth.ldapgroup'),
        ),
        migrations.AlterField(
            model_name='gcpaccount',
            name='account_id',
            field=models.CharField(default='TBD', max_length=30, verbose_name='Billing ID'),
        ),
    ]
