# Generated by Django 5.0 on 2024-09-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_image_name_alter_network_name_alter_pool_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='cpu_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='memory_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='override',
            field=models.BooleanField(default=False),
        ),
    ]
