# Generated by Django 4.1.7 on 2024-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_image_name_alter_network_name_alter_pool_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='cpu_override',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='memory_override',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='override',
            field=models.BooleanField(default=False),
        ),
    ]
