# Generated by Django 3.2.13 on 2023-03-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UmTollCallDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('deptid', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=60, null=True)),
                ('user_name', models.CharField(blank=True, max_length=401, null=True)),
                ('user_defined_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subscriber_id', models.CharField(blank=True, max_length=7, null=True)),
                ('chartcom', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('multiple_locations_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('building', models.CharField(blank=True, max_length=36, null=True)),
                ('floor', models.CharField(blank=True, max_length=18, null=True)),
                ('room', models.CharField(blank=True, max_length=18, null=True)),
                ('jack', models.CharField(blank=True, max_length=30, null=True)),
                ('connect_date', models.DateField(blank=True, null=True)),
                ('display_connect_date', models.CharField(blank=True, max_length=10, null=True)),
                ('display_connect_time', models.CharField(blank=True, max_length=5, null=True)),
                ('usage_subtype_code', models.CharField(max_length=20)),
                ('to_number', models.CharField(blank=True, max_length=80, null=True)),
                ('from_number', models.CharField(blank=True, max_length=80, null=True)),
                ('location', models.CharField(blank=True, max_length=29, null=True)),
                ('call_classification', models.CharField(blank=True, max_length=40, null=True)),
                ('call_description', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('call_duration', models.FloatField(blank=True, null=True)),
                ('dur_mn', models.FloatField(blank=True, null=True)),
                ('dur_ss', models.FloatField(blank=True, null=True)),
                ('amount_billed', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_toll_call_detail_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('report_year', models.IntegerField()),
                ('report_month', models.CharField(max_length=10)),
                ('report_type', models.CharField(max_length=10)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_by', models.CharField(max_length=20)),
            ],
        ),
    ]
