# Generated by Django 4.1.7 on 2023-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_month', models.CharField(max_length=10)),
                ('bill_year', models.CharField(max_length=10)),
                ('dept_id', models.CharField(max_length=10)),
                ('report_type', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
