# Generated by Django 4.1.7 on 2023-04-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField()),
                ('bill_year', models.IntegerField()),
                ('bill_month', models.CharField(max_length=10)),
                ('report_type', models.CharField(max_length=10)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
