# Generated by Django 4.1.7 on 2023-04-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RenameField(
            model_name='downloadlog',
            old_name='report_month',
            new_name='bill_month',
        ),
        migrations.RenameField(
            model_name='downloadlog',
            old_name='report_year',
            new_name='bill_year',
        ),
        migrations.RenameField(
            model_name='downloadlog',
            old_name='department_id',
            new_name='dept_id',
        ),
        migrations.RemoveField(
            model_name='downloadlog',
            name='clicked_by',
        ),
    ]
