# Generated by Django 5.1.6 on 2025-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_downloadlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalTelephoneServiceMetricsClickLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
