# Generated by Django 4.1.9 on 2023-05-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_downloadlog'),
        ('reports', '0003_delete_log_and_more'),
    ]

    operations = [
    ]
