# Generated by Django 3.1.12 on 2021-06-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('wo_number_display', models.CharField(max_length=14)),
                ('pre_order_number', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=32, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=32, null=True)),
                ('woid', models.IntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Complete'), (2, 'Open'), (3, 'Rework')], null=True)),
                ('percent_completed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('health', models.PositiveSmallIntegerField(choices=[(1, 'Red'), (2, 'Yellow'), (3, 'Green')], null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('legacy_parent_id', models.CharField(default=0, max_length=32)),
                ('estimate_id', models.IntegerField()),
                ('status_name', models.CharField(max_length=60)),
                ('project_display', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'um_bom_project_v',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BOM Created'), (2, 'BOM - Notify Warehouse'), (3, 'BOM - Material Ordered'), (4, 'BOM Completed'), (5, 'BOM Cancelled'), (0, 'BOM Rejected'), (11, 'NetOps Created'), (12, 'BOM - Route to Project Manager')]),
        ),
    ]
