# Generated by Django 5.0 on 2024-07-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='unity',
            name='phone_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unity',
            name='temp_pin',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
