# Generated by Django 5.0 on 2024-07-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_unity_phone_number_unity_temp_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unity',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
