# Generated by Django 6.0 on 2026-05-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0004_alter_unity_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100)),
                ('seq_num', models.PositiveIntegerField(default=0)),
                ('help_text', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, help_text='Internal=app:view_name  External=full https url', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.menuitem')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'ordering': ['seq_num'],
            },
        ),
    ]
