# Generated by Django 3.1.2 on 2020-12-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_umrteinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmBomProcurementUsersV',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('security_role_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."UM_BOM_PROCUREMENT_USERS_V',
                'managed': False,
            },
        ),
    ]
