# Generated by Django 5.1.6 on 2026-01-07 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_unity_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),

        migrations.RunSQL(
            sql="""
                INSERT INTO SRS_PROJECT_CHOICESET (CODE, LABEL, DESCRIPTION, IS_ACTIVE)
                VALUES ('TBD', 'Default', '', 1)
            """,
            reverse_sql="""
                DELETE FROM PROJECT_CHOICESET WHERE CODE = 'TBD'
            """,
        ),

        migrations.AddField(
            model_name='choice',
            name='set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.choiceset'),
            preserve_default=False,
        ),
    ]
