# Generated by Django 3.1.12 on 2021-06-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.IntegerField()),
                ('success', models.BooleanField()),
                ('notified', models.BooleanField()),
            ],
        ),
    ]
