# Generated by Django 3.1.12 on 2021-06-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_webhooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webhooks',
        ),
    ]
