# Generated by Django 3.2.4 on 2021-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_ummpathdwcurrdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmOscAcctChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqname', models.CharField(max_length=8)),
                ('user_defined_id', models.CharField(max_length=20)),
                ('mrc_account_number', models.CharField(max_length=100)),
                ('toll_account_number', models.CharField(max_length=100)),
                ('local_account_number', models.CharField(max_length=100)),
                ('date_added', models.DateField(null=True)),
                ('old_dept_full_name', models.CharField(max_length=100)),
                ('old_dept_mgr', models.CharField(max_length=100)),
                ('user_full_name', models.CharField(max_length=100)),
                ('new_dept_full_name', models.CharField(max_length=100)),
                ('new_dept_mgr', models.CharField(max_length=100)),
                ('new_chartfield', models.CharField(max_length=100)),
                ('new_shortcode', models.CharField(max_length=100)),
                ('optional_message', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=2000)),
                ('old_chartfield', models.CharField(max_length=100)),
                ('old_shortcode', models.CharField(max_length=100)),
                ('new_dept_mgr_uniqname', models.CharField(max_length=100)),
                ('old_dept_mgr_uniqname', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('rejected_by', models.CharField(max_length=100)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_osc_acct_change_requests',
                'ordering': ('batch',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UmOscAuthUsersApi',
            fields=[
                ('um_osc_auth_users_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'PS_RATING"."UM_OSC_AUTH_USERS_API_V',
                'managed': False,
            },
        ),
    ]
