# Generated by Django 3.2.4 on 2022-02-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_ummpathdwcurrdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmOscAcctChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqname', models.CharField(max_length=8)),
                ('user_defined_id', models.CharField(max_length=20)),
                ('mrc_account_number', models.CharField(max_length=100)),
                ('toll_account_number', models.CharField(max_length=100)),
                ('local_account_number', models.CharField(max_length=100)),
                ('date_added', models.DateField(null=True)),
                ('old_dept_full_name', models.CharField(max_length=100)),
                ('old_dept_mgr', models.CharField(max_length=100)),
                ('user_full_name', models.CharField(max_length=100)),
                ('new_dept_full_name', models.CharField(max_length=100)),
                ('new_dept_mgr', models.CharField(max_length=100)),
                ('new_chartfield', models.CharField(max_length=100)),
                ('new_shortcode', models.CharField(max_length=100)),
                ('optional_message', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=2000)),
                ('old_chartfield', models.CharField(max_length=100)),
                ('old_shortcode', models.CharField(max_length=100)),
                ('new_dept_mgr_uniqname', models.CharField(max_length=100)),
                ('old_dept_mgr_uniqname', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('rejected_by', models.CharField(max_length=100)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_osc_acct_change_requests',
                'ordering': ('batch',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UmOscAuthUsersApi',
            fields=[
                ('um_osc_auth_users_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'PS_RATING"."UM_OSC_AUTH_USERS_API_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UmOscNameChangeV',
            fields=[
                ('deptid', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=15, null=True)),
                ('service_number', models.CharField(db_collation='USING_NLS_COMP', max_length=60)),
                ('service_status_code', models.CharField(db_collation='USING_NLS_COMP', max_length=15)),
                ('service_type', models.CharField(db_collation='USING_NLS_COMP', max_length=20)),
                ('subscriber_id', models.CharField(db_collation='USING_NLS_COMP', max_length=7, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=50, null=True)),
                ('mi', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=1, null=True)),
                ('last_name', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=50, null=True)),
                ('email_address', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=320, null=True)),
                ('uniqname', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=320, null=True)),
                ('subscriber_status', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=20, null=True)),
                ('user_defined_id', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location_id', models.FloatField()),
                ('building_code', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=10, null=True)),
                ('building_name', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=25, null=True)),
                ('floor_name', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=18, null=True)),
                ('room_name', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=18, null=True)),
                ('jack_name', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=30, null=True)),
                ('cable_path_id', models.FloatField(blank=True, null=True)),
                ('dept_default_exp_chartfield', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=100, null=True)),
                ('occ_exp_chartfield', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=100, null=True)),
                ('mrc_exp_chartfield', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=100, null=True)),
                ('toll_exp_chartfield', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=100, null=True)),
                ('local_exp_chartfield', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=100, null=True)),
                ('other_exp_chartfield', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=100, null=True)),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_osc_name_change_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=200)),
                ('data', models.JSONField()),
            ],
        ),
    ]
