# Generated by Django 3.2.4 on 2022-07-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_actionlog_umoscacctchangerequest_umoscauthusersapi_umoscnamechangev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('sender', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('cc', models.CharField(blank=True, max_length=100, null=True)),
                ('bcc', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
