# Generated by Django 3.2 on 2022-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('status', models.CharField(max_length=1)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'srs_dept_group_v',
                'managed': False,
            },
        ),
    ]
