# Generated by Django 3.2.4 on 2022-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'PINN_CUSTOM"."um_softphone_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeptV',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
                ('selections_made', models.IntegerField()),
                ('remaining', models.IntegerField()),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_softphone_dept_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('subscriber', models.IntegerField(primary_key=True, serialize=False)),
                ('uniqname_correct', models.CharField(choices=[(None, '---'), ('YES', 'Yes'), ('CHANGE', 'No'), ('NA', 'Not Applicable')], max_length=12)),
                ('uniqname', models.CharField(max_length=8)),
                ('migrate', models.CharField(max_length=12)),
                ('location_correct', models.BooleanField(null=True)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('other_category', models.CharField(blank=True, max_length=80, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=8, null=True)),
                ('service_id', models.IntegerField(null=True)),
                ('service_number', models.CharField(max_length=60, null=True)),
                ('location_id', models.IntegerField(null=True)),
                ('building_code', models.CharField(max_length=10, null=True)),
                ('building', models.CharField(max_length=25, null=True)),
                ('floor', models.CharField(max_length=18, null=True)),
                ('room', models.CharField(max_length=18, null=True)),
                ('jack', models.CharField(max_length=30, null=True)),
                ('cable_path_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_softphone_selection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelectionV',
            fields=[
                ('subscriber', models.IntegerField(primary_key=True, serialize=False)),
                ('uniqname_correct', models.CharField(choices=[(None, '---'), ('YES', 'Yes'), ('CHANGE', 'No'), ('NA', 'Not Applicable')], max_length=12)),
                ('uniqname', models.CharField(max_length=8)),
                ('migrate', models.CharField(max_length=12)),
                ('location_correct', models.BooleanField(null=True)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('other_category', models.CharField(blank=True, max_length=80, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=8, null=True)),
                ('service_id', models.IntegerField(null=True)),
                ('service_number', models.CharField(max_length=60, null=True)),
                ('location_id', models.IntegerField(null=True)),
                ('building_code', models.CharField(max_length=10, null=True)),
                ('building', models.CharField(max_length=25, null=True)),
                ('floor', models.CharField(max_length=18, null=True)),
                ('room', models.CharField(max_length=18, null=True)),
                ('jack', models.CharField(max_length=30, null=True)),
                ('cable_path_id', models.IntegerField(null=True)),
                ('dept_id', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_softphone_selection_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriberCharges',
            fields=[
                ('subscriber', models.IntegerField(primary_key=True, serialize=False)),
                ('uniqname_correct', models.CharField(choices=[(None, '---'), ('YES', 'Yes'), ('CHANGE', 'No'), ('NA', 'Not Applicable')], max_length=12)),
                ('uniqname', models.CharField(max_length=8)),
                ('migrate', models.CharField(max_length=12)),
                ('location_correct', models.BooleanField(null=True)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('other_category', models.CharField(blank=True, max_length=80, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=8, null=True)),
                ('service_id', models.IntegerField(null=True)),
                ('service_number', models.CharField(max_length=60, null=True)),
                ('location_id', models.IntegerField(null=True)),
                ('building_code', models.CharField(max_length=10, null=True)),
                ('cable_path_id', models.IntegerField(null=True)),
                ('current_uniqname', models.CharField(max_length=8)),
                ('current_first_name', models.CharField(max_length=200)),
                ('current_last_name', models.CharField(max_length=200)),
                ('dept_id', models.CharField(max_length=10)),
                ('subscriber_id', models.CharField(max_length=10)),
                ('user_defined_id', models.CharField(max_length=10)),
                ('building', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('jack', models.CharField(max_length=10)),
                ('location_since_date', models.CharField(max_length=10)),
                ('charges', models.JSONField()),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_softphone_v',
                'managed': False,
            },
        ),
    ]
