# Generated by Django 4.1.2 on 2022-10-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutDate',
            fields=[
                ('cut_date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
