# Generated by Django 3.2 on 2022-08-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_departmentgroup'),
        ('softphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuoUser',
            fields=[
                ('service_number', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('uniqname', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_softphone_duo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zoom',
            fields=[
                ('elg', models.CharField(max_length=1)),
                ('elg_code', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('type', models.IntegerField(null=True)),
                ('timezone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('last_login_time', models.DateTimeField()),
                ('phone_country', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_softphone_zoom',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='selectionv',
            options={'managed': False, 'verbose_name': 'Selection', 'verbose_name_plural': 'Selection Report'},
        ),
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=8)),
                ('dept_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.departmentgroup')),
            ],
            options={
                'db_table': 'srs_ambassador',
            },
        ),
    ]
