# Generated by Django 3.2.13 on 2023-03-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softphone', '0002_cutdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomToken',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_zoom_token',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'ordering': ['sequence'], 'verbose_name_plural': 'Categories'},
        ),
    ]
