# Generated by Django 4.1.7 on 2024-07-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softphone', '0003_zoomtoken_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectionv',
            options={'managed': False, 'verbose_name': 'Selection'},
        ),
    ]
