# Generated by Django 4.1.9 on 2023-05-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softphone', '0003_auto_20230322_1235'),
        ('softphone', '0003_zoomtoken_alter_category_options'),
    ]

    operations = [
    ]
