# Generated by Django 5.1.6 on 2025-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softphone', '0004_alter_selectionv_options'),
        ('softphone', '0004_zoomapi_alter_selectionv_options'),
    ]

    operations = [
    ]
