# Generated by Django 6.0 on 2026-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softphone', '0005_wolflocation_wolfresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='wolfresponse',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wolfresponse',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
