# Generated by Django 6.0 on 2026-04-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softphone', '0006_wolfresponse_submitted_at_wolfresponse_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wolfresponse',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wolfresponse',
            name='action',
            field=models.CharField(blank=True, choices=[('DISCONNECT', 'Disconnect'), ('SOFTPHONE_USER', 'Upgrade to Zoom Softphone'), ('DESKPHONE_USER', 'Upgrade to Zoom Deskphone'), ('DESKPHONE_COMMON', 'Upgrade to Zoom Common Area Deskphone'), ('KEEP_ANALOG', 'Keep analog (for compliance, alarms, fax, modem, emergency)')], max_length=25, null=True),
        ),
    ]
