apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup-schedule-{namespace}
  namespace: openshift-adp
spec:
  schedule: 0 1 * * *
  template:
    excludedResources:
    - events.events.k8s.io
    - events
    includedNamespaces:
    - { namespace being created }
    defaultVolumesToRestic: true
    ttl: 168h0m0s
