apiVersion: v1
kind: LimitRange
metadata:
  name: core-resource-limits
spec:
  limits:
  - default:
      cpu: "2"
      memory: 8Gi
    defaultRequest:
      cpu: 200m
      memory: 1600Mi
    max:
      cpu: "2"
      memory: 8Gi
    type: Container