apiVersion: v1
kind: LimitRange
metadata:
  name: core-resource-limits
spec:
  limits:
  - default:
      cpu: "1"
      memory: 4Gi
    defaultRequest:
      cpu: 100m
      memory: 800Mi
    max:
      cpu: "1"
      memory: 4Gi
    type: Container