apiVersion: v1
kind: LimitRange
metadata:
  name: core-resource-limits
spec:
  limits:
  - default:
      cpu: 250m
      memory: 1Gi
    defaultRequest:
      cpu: 25m
      memory: 200Mi
    max:
      cpu: 250m
      memory: 1Gi
    type: Container