apiVersion: batch/v1
kind: CronJob
metadata:
  name: shortcode-audit
spec:
  schedule: '30 8 * * 1,3,5'
  timeZone: America/Detroit
  ConcurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: dailycron
        spec:
          containers:
            -
              name: batch
              image: 'image-registry.openshift-image-registry.svc:5000/srs/production'
              envFrom:
              - configMapRef:
                  name: production
              command:
                - python3
                - manage.py
                - shortcode_audit
          restartPolicy: Never