# Send every Tuesday at 10 AM
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: softphone-tuesday
spec:
  schedule: '0 10 * * 2'
  ConcurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: dailycron
        spec:
          containers:
            -
              name: batch
              image: 'docker-registry.default.svc:5000/srs/qa'
              envFrom:
              - configMapRef:
                  name: qa
              command: ["python3",  "manage.py", "softphone_email", "--email", "TUE_NO_LOGIN"]
          restartPolicy: Never
