# Send every Wednesday at 12:30 PM
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: softphone-wednesday
spec:
  schedule: '30 12 * * 3'
  ConcurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: dailycron
        spec:
          containers:
            -
              name: batch
              image: 'docker-registry.default.svc:5000/srs/qa'
              envFrom:
              - configMapRef:
                  name: qa
              command: ["python3",  "manage.py", "softphone_email", "--email", "WED_NO_LOGIN"]
          restartPolicy: Never
