# Send every Monday at 10 AM
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: softphone-monday
spec:
  schedule: '0 10 * * 1'
  ConcurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: dailycron
        spec:
          containers:
            -
              name: batch
              image: 'docker-registry.default.svc:5000/srs/production'
              envFrom:
              - configMapRef:
                  name: production
              command: ["python3",  "manage.py", "softphone_email", "--email", "USER_MIGRATE"]
          restartPolicy: Never
