# Run on the 15th of every month at 5 AM
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: production-turbo
spec:
  schedule: '37 3 15 * *'
  ConcurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: dailycron
        spec:
          containers:
            -
              name: batch
              image: 'docker-registry.default.svc:5000/srs/production'
              envFrom:
              - configMapRef:
                  name: production
              command:
                - python3
                - manage.py
                - upload_storage_billing
                - Turbo
          restartPolicy: OnFailure
