# Generated by Django 4.1.7 on 2023-05-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='health',
        ),
        migrations.RemoveField(
            model_name='project',
            name='percent_completed',
        ),
        migrations.AddField(
            model_name='estimate',
            name='engineer_status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('NOT_COMPLETE', 'Not Complete')], default='NOT_COMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'Estimate'), (6, 'Approved'), (2, 'Warehouse'), (3, 'Ordered'), (4, 'Completed'), (5, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Complete'), (2, 'Open'), (4, 'In Progress')], null=True),
        ),
    ]
