# Generated by Django 4.1.7 on 2023-05-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Complete'), (2, 'Open'), (4, 'In Progress')], null=True),
        ),
    ]
