# Generated by Django 4.1.9 on 2023-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='engineer_status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('NOT_COMPLETE', 'Not Complete')], default='NOT_COMPLETE', max_length=20),
        ),
    ]
