# Generated by Django 3.2.4 on 2022-02-12 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=32, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=32, null=True)),
                ('woid', models.IntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'Estimate'), (2, 'Warehouse'), (3, 'Ordered'), (4, 'Completed'), (5, 'Cancelled')], default=1)),
                ('label', models.CharField(max_length=20)),
                ('contingency_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('contingency_percentage', models.IntegerField(default=0, null=True)),
                ('folder', models.URLField(blank=True, null=True)),
                ('legacy_data', models.TextField(null=True)),
                ('legacy_id', models.CharField(default=0, max_length=32)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.technician')),
            ],
            options={
                'db_table': 'um_bom_estimate',
                'permissions': (('can_access_bom', 'Base Access - Add, View & Create Estimates'), ('can_update_bom_ordered', 'Warehouse - Update Material after estimate stage')),
            },
        ),
        migrations.CreateModel(
            name='LegacyData',
            fields=[
                ('create_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=32, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=32, null=True)),
                ('sys_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('parent_sys_id', models.CharField(max_length=32, null=True)),
                ('record_name', models.CharField(max_length=32)),
                ('new_record_id', models.IntegerField(null=True)),
                ('multi', models.IntegerField(null=True)),
                ('woid', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('commodity_id', models.IntegerField(null=True)),
                ('commodity_code', models.CharField(max_length=32, null=True)),
                ('commodity_descr', models.CharField(max_length=200, null=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('contingency_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('contingency_percentage', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('location_name', models.CharField(max_length=200, null=True)),
                ('location_descr', models.CharField(max_length=1000, null=True)),
                ('assigned_engineer', models.IntegerField(null=True)),
                ('addl_1', models.CharField(max_length=200, null=True)),
                ('addl_2', models.CharField(max_length=200, null=True)),
                ('data', models.TextField()),
                ('vendor', models.CharField(default='', max_length=50)),
                ('reel_number', models.CharField(default='', max_length=20)),
                ('staged', models.BooleanField(default=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('estimated_receive_date', models.DateField(blank=True, null=True)),
                ('release_number', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'um_bom_legacy_data',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.PositiveSmallIntegerField(choices=[(1, 'BOM Created'), (2, 'BOM - Notify Warehouse'), (3, 'BOM - Material Ordered'), (4, 'BOM Completed'), (5, 'BOM Cancelled'), (0, 'BOM Rejected'), (11, 'NetOps Created'), (12, 'BOM - Route to Project Manager')])),
                ('recipient', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'um_bom_notification',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=32, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=32, null=True)),
                ('woid', models.IntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Complete'), (2, 'Open'), (3, 'Rework')], null=True)),
                ('percent_completed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('health', models.PositiveSmallIntegerField(choices=[(1, 'Red'), (2, 'Yellow'), (3, 'Green')], null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('activity', models.TextField(default='')),
                ('legacy_parent_id', models.CharField(default=0, max_length=32)),
                ('netops_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.technician', verbose_name='NetOps')),
            ],
            options={
                'db_table': 'um_bom_project',
            },
        ),
        migrations.CreateModel(
            name='MaterialLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=32, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=32, null=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(null=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.estimate')),
            ],
            options={
                'db_table': 'um_bom_material_location',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=32, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=32, null=True)),
                ('item_code', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=50)),
                ('manufacturer_part_number', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Estimate'), (2, 'In Stock'), (3, 'Ordered')], default=1)),
                ('vendor', models.CharField(blank=True, default='', max_length=50)),
                ('reel_number', models.CharField(blank=True, default='', max_length=20)),
                ('staged', models.BooleanField(default=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('estimated_receive_date', models.DateField(blank=True, null=True)),
                ('release_number', models.CharField(blank=True, default='', max_length=50)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.item')),
                ('material_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.materiallocation')),
            ],
            options={
                'db_table': 'um_bom_material',
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=32, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('rate_type', models.PositiveSmallIntegerField(choices=[(1, 'Standard'), (2, 'Overtime')], default=1)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.estimate')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.laborgroup')),
            ],
            options={
                'db_table': 'um_bom_labor',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'um_bom_favorites',
            },
        ),
    ]
