# Generated by Django 4.1.7 on 2024-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_project_health_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrsRteVsEstimate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wo_tcom_id', models.FloatField()),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_code', models.CharField(blank=True, max_length=3, null=True)),
                ('assn_wo_group_code', models.CharField(blank=True, max_length=32, null=True)),
                ('assigned_labor_code', models.CharField(blank=True, max_length=9, null=True)),
                ('labor_code', models.CharField(blank=True, max_length=9, null=True)),
                ('reported_hours', models.FloatField(blank=True, null=True)),
                ('est_hours', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PINN_CUSTOM.srs_rte_vs_estimate',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BOM Created'), (2, 'BOM - Notify Warehouse (Send Email)'), (3, 'BOM - Material Ordered (Send Email)'), (4, 'BOM Completed'), (5, 'BOM Cancelled'), (0, 'BOM Rejected'), (11, 'NetOps Created'), (12, 'BOM - Route to Project Manager (Send Email)')]),
        ),
    ]
