# Generated by Django 5.1.6 on 2025-07-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_project_health_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='legacy_parent_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='netops_engineer',
            new_name='engineer1',
        ),
        migrations.AlterField(
            model_name='project',
            name='engineer1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer1', to='apps.technician', verbose_name='UMNET Engineer 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='engineer2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer2', to='apps.technician', verbose_name='UMNET Engineer 2'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BOM Created'), (2, 'BOM - Notify Warehouse (Send Email)'), (3, 'BOM - Material Ordered (Send Email)'), (4, 'BOM Completed'), (5, 'BOM Cancelled'), (0, 'BOM Rejected'), (11, 'NetOps Created'), (12, 'BOM - Route to Project Manager (Send Email)')]),
        ),
    ]
