# Generated by Django 4.1.7 on 2023-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_project_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BOM Created'), (2, 'BOM - Notify Warehouse (Send Email)'), (3, 'BOM - Material Ordered (Send Email)'), (4, 'BOM Completed'), (5, 'BOM Cancelled'), (0, 'BOM Rejected'), (11, 'NetOps Created'), (12, 'BOM - Route to Project Manager (Send Email)')]),
        ),
    ]
