# Generated by Django 5.1.6 on 2025-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_project_health_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_code', models.CharField(max_length=32)),
                ('commodity_name', models.CharField(max_length=200)),
                ('manufacturer_part_nbr', models.CharField(max_length=50)),
                ('min_reorder_lvl', models.IntegerField()),
                ('warehouse_code', models.CharField(max_length=32)),
                ('warehouse_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'srs_bar_code_labels_v',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BOM Created'), (2, 'BOM - Notify Warehouse (Send Email)'), (3, 'BOM - Material Ordered (Send Email)'), (4, 'BOM Completed'), (5, 'BOM Cancelled'), (0, 'BOM Rejected'), (11, 'NetOps Created'), (12, 'BOM - Route to Project Manager (Send Email)')]),
        ),
    ]
