# Generated by Django 4.1.7 on 2024-08-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_srsrtevsestimate_alter_notification_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAllTechs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelTable(
            name='srsrtevsestimate',
            table='PINN_CUSTOM.SRS_RTE_VS_ESTIMATE',
        ),
    ]
