# Generated by Django 4.1.7 on 2023-05-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_project_health_and_more'),
        ('apps', '0003_remove_project_health_and_more'),
    ]

    operations = [
    ]
