# Generated by Django 5.1.7 on 2026-04-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_bom_project_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BOM Created'), (2, 'BOM - Notify Warehouse (Send Email)'), (3, 'BOM - Material Ordered (Send Email)'), (4, 'BOM Completed'), (5, 'BOM Cancelled'), (0, 'BOM Rejected'), (6, 'BOM Approved'), (11, 'NetOps Created'), (12, 'BOM - Route to Project Manager (Send Email)')]),
        ),
    ]
