# Generated by Django 5.1.6 on 2025-05-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_itembarcode_alter_notification_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itembarcode',
            options={'managed': False, 'verbose_name': 'Item Barcode'},
        ),
    ]
