# Generated by Django 6.0 on 2026-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_bom_project_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='legacy_data',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='legacy_id',
        ),
        migrations.AddField(
            model_name='estimate',
            name='permit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BOM Created'), (2, 'BOM - Notify Warehouse (Send Email)'), (3, 'BOM - Material Ordered (Send Email)'), (4, 'BOM Completed'), (5, 'BOM Cancelled'), (0, 'BOM Rejected'), (6, 'BOM Approved'), (11, 'NetOps Created'), (12, 'BOM - Route to Project Manager (Send Email)')]),
        ),
    ]
