# Generated by Django 4.1.7 on 2024-08-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_submitalltechs_alter_srsrtevsestimate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='srsrtevsestimate',
            table='SRS_RTE_VS_ESTIMATE',
        ),
    ]
