# Generated by Django 4.1.7 on 2024-08-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_srsrtevsestimate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='srsrtevsestimate',
            table='srs_rte_vs_estimate',
        ),
    ]
