# Generated by Django 5.1.6 on 2025-05-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_itembarcode_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itembarcode',
            table='PINN_CUSTOM"."srs_bar_code_labels_v',
        ),
    ]
