# Generated by Django 4.1.7 on 2024-08-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_srsrtevsestimate_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitAllTechs',
        ),
        migrations.AlterModelTable(
            name='srsrtevsestimate',
            table='PINN_CUSTOM.srs_rte_vs_estimate',
        ),
    ]
