# Generated by Django 4.1.7 on 2024-12-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_srsrtevsestimate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='srsrtevsestimate',
            table='PINN_CUSTOM.SRS_RTE_VS_ESTIMATE',
        ),
    ]
