# Generated by Django 4.1.7 on 2024-12-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_srsrtevsestimate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='srsrtevsestimate',
            table='PINN_CUSTOM"."srs_rte_vs_estimate',
        ),
    ]
