# Generated by Django 2.2 on 2019-04-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='category',
        ),
    ]
