# Generated by Django 2.1.5 on 2019-03-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='steps',
            field=models.ManyToManyField(to='order.Step'),
        ),
    ]
