# Generated by Django 3.2.13 on 2022-12-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userchartcomv',
            table='order_user_chartcom_v',
        ),
    ]
