# Generated by Django 4.1.2 on 2022-10-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userchartcomv',
            table='order_user_chartcom_v',
        ),
    ]
