# Generated by Django 2.2 on 2019-04-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190409_0821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
