# Generated by Django 2.2 on 2019-04-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_feature_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinnServiceProfile',
        ),
    ]
