# Generated by Django 4.1.7 on 2023-05-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_step_custom_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='production',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
