# Generated by Django 2.1.5 on 2019-03-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190318_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='service',
            name='features',
        ),
        migrations.RemoveField(
            model_name='service',
            name='products',
        ),
        migrations.RemoveField(
            model_name='service',
            name='steps',
        ),
        migrations.AddField(
            model_name='action',
            name='features',
            field=models.ManyToManyField(blank=True, to='order.Feature'),
        ),
        migrations.AddField(
            model_name='action',
            name='products',
            field=models.ManyToManyField(blank=True, to='order.Product'),
        ),
        migrations.AddField(
            model_name='action',
            name='route',
            field=models.CharField(choices=[('P', 'Preorder'), ('I', 'Incident'), ('E', 'Email')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='action',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='steps',
            field=models.ManyToManyField(to='order.Step'),
        ),
    ]
