# Generated by Django 2.2 on 2019-04-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_delete_pinnserviceprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.ManyToManyField(to='order.FeatureCategory'),
        ),
    ]
