# Generated by Django 4.1.7 on 2024-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_step_custom_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='production',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='backup',
            field=models.BooleanField(default=True),
        ),
    ]
