# Generated by Django 2.2 on 2019-04-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '__first__'),
        ('order', '0004_feature_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='service',
        ),
        migrations.AddField(
            model_name='item',
            name='action',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='umoscpreorderapiv_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.UmOscPreorderApiV'),
            preserve_default=False,
        ),
    ]
