# Generated by Django 2.1.5 on 2019-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190319_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='destination',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
