# Generated by Django 2.2 on 2019-04-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='custom_form',
            field=models.CharField(choices=[('', ''), ('FeaturesForm', 'Features'), ('EquipmentForm', 'Incident'), ('RestrictionsForm', 'Restrictions')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='display_seq_no',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Action')),
            ],
        ),
    ]
