# Generated by Django 5.0 on 2024-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_server_legacy_data_server_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartcom',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
