# Generated by Django 5.1.6 on 2025-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_server_legacy_data_server_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTicket',
            fields=[
                ('ticket_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('summary', models.TextField()),
                ('comments', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'order_server_ticket_v',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='server',
            name='cname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
