# Generated by Django 5.1.4 on 2025-06-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_server_legacy_data_server_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcinstance',
            name='college',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
