# Generated by Django 2.1.5 on 2019-03-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_action_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='destination',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='action',
            name='display_seq_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
