# Generated by Django 5.1.6 on 2025-11-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_serverticket_arcinstance_college_server_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='billable',
            field=models.BooleanField(default=True, help_text='Turning this off will pause monthly billing.'),
        ),
    ]
