# Generated by Django 5.1.15 on 2025-12-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_serverticket_arcinstance_college_server_cname'),
    ]

    operations = [

        migrations.CreateModel(
            name='StorageBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('shortcode', models.CharField(max_length=100)),
                ('storage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcodes', to='order.storageinstance')),
            ],
        ),
    ]
