# Generated by Django 2.2 on 2019-04-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190404_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='service',
        ),
        migrations.AddField(
            model_name='item',
            name='action',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Cart'),
            preserve_default=False,
        ),
    ]
