# Generated by Django 2.1.5 on 2019-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0011_auto_20190307_1357'),
        ('order', '0006_auto_20190319_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnServiceProfile',
            fields=[
                ('deptid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service_number', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PINN_CUSTOM"."um_osc_service_profile_v',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='action',
            name='roles',
            field=models.ManyToManyField(blank=True, to='oscauth.Role'),
        ),
    ]
