# Generated by Django 2.2 on 2019-04-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190414_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('display_seq_no', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('', ''), ('YN', 'Yes/No'), ('ST', 'String'), ('NU', 'Number')], max_length=2)),
                ('target', models.CharField(max_length=80)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Step')),
            ],
        ),
    ]
