# Generated by Django 5.1.15 on 2025-12-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_arcinstance_college_server_billable'),
        ('order', '0007_arcinstance_college_storagebilling'),
    ]

    operations = [
    ]
