# Generated by Django 2.2 on 2019-04-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190404_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
    ]
