# Generated by Django 5.1.7 on 2026-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_merge_20251207_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='transformation',
            field=models.BooleanField(blank=True, help_text='Indicates whether the server was brought in as part of the IT transformation effort.', null=True),
        ),
    ]
