# Generated by Django 2.1.5 on 2019-02-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='order',
            new_name='cart',
        ),
    ]
