# Generated by Django 2.2 on 2019-04-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_item_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
