# Generated by Django 2.2 on 2019-04-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190415_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='label',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='add_info_checkbox_4',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_info_text_7',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='custom_form',
            field=models.CharField(choices=[('', ''), ('LocationForm', 'Location'), ('EquipmentForm', 'Equipment'), ('NewLocationForm', 'New Location'), ('ReviewForm', 'Review'), ('ChartfieldForm', 'Chartfield'), ('RestrictionsForm', 'Restrictions'), ('FeaturesForm', 'Features')], max_length=20),
        ),
    ]
