# Generated by Django 2.1.5 on 2019-03-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190323_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='roles',
        ),
    ]
