# Generated by Django 6.0 on 2026-03-24 16:23

import django.db.models.deletion
import django.utils.timezone
import project.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_arcinstance_college_server_transformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortcode', project.models.ShortCodeField(help_text='Six digit shortcode for billing purposes.', max_length=6)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('public_facing', models.BooleanField(default=False)),
                ('production', models.BooleanField(default=True)),
                ('managed', models.BooleanField(default=True)),
                ('cpu', models.IntegerField(verbose_name='CPU')),
                ('ram', models.IntegerField(verbose_name='RAM')),
                ('replicated', models.BooleanField(default=True)),
                ('on_call', models.PositiveSmallIntegerField(choices=[(0, 'Business Hours'), (1, '24/7')], null=True)),
                ('in_service', models.BooleanField(default=True)),
                ('billable', models.BooleanField(default=True, help_text='Turning this off will pause monthly billing.')),
                ('firewall', models.CharField(max_length=100)),
                ('backup', models.BooleanField(default=True)),
                ('support_email', models.CharField(max_length=100)),
                ('support_phone', models.CharField(max_length=100)),
                ('transformation', models.BooleanField(blank=True, help_text='Indicates whether the server was brought in as part of the IT transformation effort.', null=True)),
                ('cname', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(max_length=100)),
                ('datacenter', models.CharField(max_length=100)),
                ('firewall_requests', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admin_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oscauth.ldapgroup')),
                ('backup_time', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'parent__code': 'SERVER_BACKUP_TIME'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.choice')),
                ('database_type', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'parent__code': 'DATABASE_TYPE'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.choice')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'parent__code__in': ['SERVER_UNMANAGED_OS', 'LINUX', 'WINDOWS']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.choice')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oscauth.ldapgroup')),
                ('patch_day', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'parent__code': 'SERVER_PATCH_DATE'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.choice')),
                ('patch_time', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'parent__code': 'SERVER_PATCH_TIME'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.choice')),
                ('reboot_day', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'parent__code': 'SERVER_REBOOT_DATE'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.choice')),
                ('reboot_time', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'parent__code': 'SERVER_REBOOT_TIME'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.choice')),
            ],
            options={
                'verbose_name': 'historical server',
                'verbose_name_plural': 'historical servers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
