# Generated by Django 5.1.7 on 2026-04-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_arcinstance_college_server_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose of this server', max_length=500, null=True),
        ),
    ]
