# Generated by Django 5.1.6 on 2026-05-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_arcinstance_college_server_transformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('HIDE', 'Hide'), ('SHOW', 'Show')], max_length=20)),
                ('target', models.CharField(max_length=50)),
                ('target_value', models.CharField(blank=True, max_length=50)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.element')),
            ],
        ),
    ]
