# Generated by Django 6.0 on 2026-04-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_arcinstance_college_historicalserver'),
        ('order', '0010_arcinstance_college_server_purpose'),
    ]

    operations = [
    ]
