# Generated by Django 2.2 on 2019-04-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190416_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
