# Generated by Django 2.1.5 on 2019-03-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_featurecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.FeatureCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featurecategory',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
