# Generated by Django 2.2 on 2019-04-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_item_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
