# Generated by Django 2.1.5 on 2019-02-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='service',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='service',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='service',
        ),
        migrations.RemoveField(
            model_name='item',
            name='service_action',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
