# Generated by Django 2.2 on 2019-04-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20190404_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
