# Generated by Django 2.2 on 2019-04-16 22:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
