# Generated by Django 2.2 on 2019-04-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=8)),
            ],
        ),
    ]
