# Generated by Django 2.1.5 on 2019-03-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20190331_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='category',
        ),
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.ManyToManyField(to='order.FeatureCategory'),
        ),
    ]
