# Generated by Django 2.2 on 2019-05-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_item_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='attributes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('', ''), ('YN', 'Yes/No'), ('Radio', 'Radio'), ('ST', 'String'), ('NU', 'Number'), ('PH', 'Phone Set Type')], max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='custom_form',
            field=models.CharField(blank=True, choices=[('', ''), ('LocationForm', 'Location'), ('EquipmentForm', 'Equipment'), ('NewLocationForm', 'New Location'), ('AddlInfoForm', 'Additional Information'), ('ReviewForm', 'Review'), ('ChartfieldForm', 'Chartfield'), ('RestrictionsForm', 'Restrictions'), ('FeaturesForm', 'Features')], max_length=20),
        ),
    ]
