# Generated by Django 2.2 on 2019-04-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
