# Generated by Django 2.2 on 2019-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20190501_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('STD', 'Standard'), ('OPT', 'Optional'), ('SPD', 'Speed Call'), ('VM', 'Voice Mail')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restriction',
            name='category',
            field=models.ManyToManyField(to='order.FeatureCategory'),
        ),
    ]
