# Generated by Django 2.1.5 on 2019-03-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20190331_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('A', 'Add'), ('M', 'Modify'), ('D', 'Disconnect'), ('E', 'Equipment')], default='A', max_length=1),
        ),
    ]
