# Generated by Django 2.2.1 on 2019-05-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20190508_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurecategory',
            options={'verbose_name_plural': 'Feature Categories'},
        ),
    ]
