# Generated by Django 2.2 on 2019-05-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20190508_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurecategory',
            options={'verbose_name_plural': 'Feature Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
