# Generated by Django 2.1.5 on 2019-03-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
