# Generated by Django 2.1.5 on 2019-03-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20190331_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='features',
        ),
        migrations.RemoveField(
            model_name='action',
            name='products',
        ),
    ]
