# Generated by Django 2.2 on 2019-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20190514_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
