# Generated by Django 2.2 on 2019-05-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20190516_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('display_seq_no', models.PositiveIntegerField()),
                ('values', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
