# Generated by Django 2.2 on 2019-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20190517_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='updated_by',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
