# Generated by Django 2.2 on 2019-05-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_business_updated_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
