# Generated by Django 2.2 on 2019-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_delete_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='service',
            name='display_seq_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
