# Generated by Django 2.2 on 2019-05-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20190517_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='restriction',
            old_name='name',
            new_name='label',
        ),
    ]
