# Generated by Django 2.2 on 2019-05-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20190516_1038'),
        ('order', '0024_auto_20190517_1004'),
    ]

    operations = [
    ]
