# Generated by Django 2.2 on 2019-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_merge_20190517_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='display_seq_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
