# Generated by Django 2.2 on 2019-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20190517_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restriction',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='display_seq_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='display_seq_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restriction',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
