# Generated by Django 2.2 on 2019-05-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20190517_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='active',
        ),
    ]
