# Generated by Django 2.2 on 2019-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_remove_feature_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
