# Generated by Django 2.2 on 2019-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_auto_20190518_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('can_order', 'Can submit orders, view cart, view order status')]},
        ),
        migrations.AlterField(
            model_name='featurecategory',
            name='display_seq_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featurecategory',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
