# Generated by Django 2.2 on 2019-05-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20190523_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'permissions': [('can_order', 'Can submit orders, view cart, view order status')]},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
