# Generated by Django 2.2 on 2019-05-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_auto_20190523_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={},
        ),
    ]
