# Generated by Django 2.2 on 2019-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20190529_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chartcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('program', models.CharField(max_length=30)),
                ('acct_class', models.CharField(max_length=30)),
                ('project_grant', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
            ],
        ),
    ]
