# Generated by Django 2.2 on 2019-05-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_chartcom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartcom',
            old_name='acct_class',
            new_name='class_code',
        ),
    ]
