# Generated by Django 2.2 on 2019-06-05 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_auto_20190531_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
    ]
