# Generated by Django 2.2 on 2019-06-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20190605_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
