# Generated by Django 2.2 on 2019-06-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_auto_20190609_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.AddField(
            model_name='item',
            name='chartcom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Chartcom'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
