# Generated by Django 2.2 on 2019-06-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_auto_20190611_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartcom',
            name='account_number',
        ),
    ]
