# Generated by Django 2.2 on 2019-06-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20190614_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChartcomV',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'order_user_chartcom',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='element',
            name='target',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('', ''), ('YN', 'Yes/No'), ('Radio', 'Radio'), ('ST', 'String'), ('NU', 'Number'), ('Chart', 'Chartcom'), ('PH', 'Phone Set Type')], max_length=20),
        ),
    ]
