# Generated by Django 2.2 on 2019-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_auto_20190616_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='display_condition',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
