# Generated by Django 2.2 on 2019-06-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_auto_20190616_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='display_condition',
        ),
    ]
