# Generated by Django 2.2 on 2019-06-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_auto_20190621_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartcom',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
