# Generated by Django 2.2 on 2019-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20190621_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecategory',
            name='label',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
