# Generated by Django 2.2 on 2019-06-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_item_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
