# Generated by Django 2.2 on 2019-08-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_auto_20190804_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cart_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('', ''), ('Radio', 'Radio'), ('ST', 'String'), ('NU', 'Number'), ('Chart', 'Chartcom')], max_length=20),
        ),
    ]
