# Generated by Django 2.2 on 2019-08-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_featuretype'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
