# Generated by Django 2.2 on 2019-08-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_feature_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.FeatureType'),
            preserve_default=False,
        ),
    ]
