# Generated by Django 2.2 on 2019-08-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_feature_type_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='type',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='type_new',
            new_name='type',
        ),

    ]
