# Generated by Django 2.2 on 2019-08-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0058_logitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('', ''), ('Radio', 'Radio'), ('ST', 'String'), ('NU', 'Number'), ('Chart', 'Chartcom'), ('Label', 'Label')], max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='custom_form',
            field=models.CharField(blank=True, choices=[('', ''), ('PhoneLocationForm', 'Phone Location'), ('EquipmentForm', 'Equipment'), ('NewLocationForm', 'New Location'), ('AddlInfoForm', 'Additional Information'), ('ReviewForm', 'Review'), ('ChartfieldForm', 'Chartfield'), ('RestrictionsForm', 'Restrictions'), ('FeaturesForm', 'Features'), ('StaticForm', 'Static Page'), ('AuthCodeForm', 'Auth Codes')], max_length=20),
        ),
    ]
