# Generated by Django 2.2 on 2019-09-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_auto_20190916_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('High', 'Expedited'), ('Medium', 'Standard'), ('Low', 'Low')], max_length=20),
        ),
    ]
