# Generated by Django 2.2 on 2019-09-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0063_auto_20190917_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='picture',
            new_name='file',
        ),
    ]
