# Generated by Django 2.2 on 2019-12-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_auto_20191119_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
