# Generated by Django 2.2 on 2020-02-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_auto_20200122_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageinstance',
            old_name='assign_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='storageinstance',
            name='charge_identifier',
        ),
        migrations.RemoveField(
            model_name='storageinstance',
            name='chartcom',
        ),
        migrations.AddField(
            model_name='storageinstance',
            name='shortcode',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('', ''), ('Radio', 'Radio'), ('ST', 'String'), ('NU', 'Number'), ('Chart', 'Chartcom'), ('Label', 'Label'), ('Checkbox', 'Checkbox'), ('McGroup', 'MCommunity Group'), ('HTML', 'Static HTML')], max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='custom_form',
            field=models.CharField(blank=True, choices=[('', ''), ('TabForm', 'Base Form'), ('PhoneLocationForm', 'Phone Location'), ('EquipmentForm', 'Equipment'), ('NewLocationForm', 'New Location'), ('AddlInfoForm', 'Additional Information'), ('ReviewForm', 'Review'), ('ChartfieldForm', 'Chartfield'), ('RestrictionsForm', 'Restrictions'), ('FeaturesForm', 'Features'), ('StaticForm', 'Static Page'), ('AuthCodeForm', 'Auth Codes'), ('AuthCodeCancelForm', 'Auth Codes'), ('CMCCodeForm', 'CMC Codes'), ('ProductForm', 'Quantity Model'), ('ContactCenterForm', 'Contact Center'), ('BillingForm', 'Billing'), ('VoicemailForm', 'Voicemail'), ('DetailsCIFSForm', 'CIFS Details'), ('DetailsNFSForm', 'NFS Details'), ('AccessCIFSForm', 'CIFS Access'), ('AccessNFSForm', 'NFS Access'), ('BillingStorageForm', 'Billing'), ('VolumeSelectionForm', 'Volume Selection')], max_length=20),
        ),
        migrations.AlterField(
            model_name='storageinstance',
            name='type',
            field=models.CharField(choices=[('NFS', 'NFS'), ('CIFS', 'CIFS')], default='NFS', max_length=4),
        ),
        migrations.CreateModel(
            name='StorageOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('SNAP', 'Snapshots'), ('REPL', 'Replication')], default='NFS', max_length=20)),
                ('storage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.StorageInstance')),
            ],
        ),
        migrations.CreateModel(
            name='StorageHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('storage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.StorageInstance')),
            ],
        ),
    ]
