# Generated by Django 2.2 on 2020-02-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0073_auto_20200203_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinstance',
            name='deptid',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storageinstance',
            name='created_date',
            field=models.DateTimeField(verbose_name='Assign Date'),
        ),
    ]
