# Generated by Django 2.2 on 2020-02-04 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0074_auto_20200204_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinstance',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='option',
            field=models.CharField(choices=[('SNAP', 'Snapshots'), ('REPL', 'Replication'), ('FLUX', 'Flux')], max_length=4),
        ),
    ]
