# Generated by Django 2.2 on 2020-02-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0075_auto_20200204_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageinstance',
            name='member',
        ),
        migrations.CreateModel(
            name='StorageMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('storage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.StorageInstance')),
            ],
        ),
    ]
