# Generated by Django 2.2 on 2020-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20200204_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('display_seq_no', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
