# Generated by Django 2.2 on 2020-02-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_storagerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinstance',
            name='rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.StorageRate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageinstance',
            name='uid',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StorageOption',
        ),
    ]
