# Generated by Django 2.2 on 2020-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0078_auto_20200211_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinstance',
            name='uid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
