# Generated by Django 2.2 on 2020-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0079_auto_20200211_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagerate',
            name='type',
            field=models.CharField(choices=[('NFS', 'NFS'), ('CIFS', 'CIFS')], default='NFS', max_length=4),
        ),
    ]
