# Generated by Django 2.2 on 2020-02-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0080_storagerate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinstance',
            name='shortcode',
            field=models.CharField(max_length=100),
        ),
    ]
