# Generated by Django 2.2 on 2020-02-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0081_auto_20200212_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinstance',
            name='flux',
            field=models.BooleanField(default=False),
        ),
    ]
