# Generated by Django 2.2 on 2020-03-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0082_storageinstance_flux'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinstance',
            name='ad_group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('', ''), ('Radio', 'Radio'), ('ST', 'String'), ('NU', 'Number'), ('Chart', 'Chartcom'), ('Label', 'Label'), ('Checkbox', 'Checkbox'), ('McGroup', 'MCommunity Group'), ('ShortCode', 'Short Code'), ('HTML', 'Static HTML')], max_length=20),
        ),
    ]
