# Generated by Django 2.2 on 2020-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0085_auto_20200412_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='storageinstance',
            name='owner_name',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.RunSQL("UPDATE order_storageinstance set owner_name = owner;"
        ),
        migrations.DeleteModel(
            name='StorageMember',
        ),
    ]
