# Generated by Django 2.2 on 2020-04-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_auto_20200419_1234'),
    ]

    operations = [
        migrations.RunSQL("insert into order_storageowner values (0,'Default');"
        ),
        migrations.RunSQL("UPDATE order_storageinstance set owner = '0';"
        ),
        migrations.AlterField(
            model_name='storageinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.StorageOwner'),
        ),
        migrations.CreateModel(
            name='StorageMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('storage_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.StorageOwner')),
            ],
        ),
    ]
