# Generated by Django 2.2 on 2020-04-19 14:40

from django.db import migrations
from django.core.management import call_command


def update_owner(apps, schema_editor):
    call_command('mctest')

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0087_auto_20200419_1254'),
    ]

    operations = [
        migrations.RunPython(update_owner),

    ]
