# Generated by Django 2.2 on 2020-05-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0088_auto_20200419_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinstance',
            name='autogrow',
            field=models.BooleanField(default=False),
        ),
    ]
