# Generated by Django 2.2 on 2020-05-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_auto_20200526_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagerate',
            name='service',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='order.Service'),
            preserve_default=False,
        ),
    ]
