# Generated by Django 2.2 on 2020-05-27 10:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_storagerate_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='override',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
