# Generated by Django 2.2 on 2020-06-06 14:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0092_action_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='override',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
