# Generated by Django 2.2 on 2020-06-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0021_ldapgroup_ldapgroupmember'),
        ('order', '0093_auto_20200606_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortcode', models.CharField(max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oscauth.LDAPGroup')),
            ],
        ),
        migrations.CreateModel(
            name='BackupNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('backup_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.BackupDomain')),
            ],
        ),
    ]
