# Generated by Django 2.2 on 2020-06-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_auto_20200610_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageinstance',
            old_name='owner',
            new_name='owner_bak',
        ),
    ]
