# Generated by Django 2.2 on 2020-06-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0022_ldapgroup_active'),
        ('order', '0096_auto_20200610_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.LDAPGroup'),
        ),
    ]
