# Generated by Django 2.2 on 2020-06-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0097_storageinstance_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdomain',
            name='days_extra_versions',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupdomain',
            name='days_only_version',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupdomain',
            name='versions_after_deleted',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupdomain',
            name='versions_while_exists',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupnode',
            name='time',
            field=models.CharField(default=30, max_length=10),
            preserve_default=False,
        ),
    ]
