# Generated by Django 2.2 on 2020-06-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0022_ldapgroup_active'),
        ('order', '0098_auto_20200615_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('shortcode', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('NFS', 'NFS'), ('CIFS', 'CIFS')], default='NFS', max_length=4)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Assign Date')),
                ('uid', models.PositiveIntegerField(null=True)),
                ('ad_group', models.CharField(blank=True, max_length=100, null=True)),
                ('nfs_group_id', models.PositiveIntegerField(null=True)),
                ('sensitive_regulated', models.BooleanField(default=False)),
                ('great_lakes', models.BooleanField(default=False)),
                ('armis', models.BooleanField(default=False)),
                ('lighthouse', models.BooleanField(default=False)),
                ('globus', models.BooleanField(default=False)),
                ('globus_ha', models.BooleanField(default=False)),
                ('thunder_x', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.LDAPGroup')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.StorageRate')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArcHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arc_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='order.ArcInstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
