# Generated by Django 2.2 on 2020-06-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0101_auto_20200618_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcinstance',
            name='mutli_protocol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arcinstance',
            name='nfs_group_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
