# Generated by Django 2.2 on 2020-06-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0102_auto_20200619_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagerate',
            name='unit_of_measure',
            field=models.CharField(choices=[('GB', 'Gigabytes'), ('TB', 'Terabytes')], default='GB', max_length=2),
        ),
    ]
