# Generated by Django 2.2 on 2020-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0103_storagerate_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcinstance',
            name='nfs_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
