# Generated by Django 2.2 on 2020-06-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0104_auto_20200619_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcinstance',
            old_name='mutli_protocol',
            new_name='multi_protocol',
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('', ''), ('Radio', 'Radio'), ('ST', 'String'), ('List', 'List'), ('NU', 'Number'), ('Chart', 'Chartcom'), ('Label', 'Label'), ('Checkbox', 'Checkbox'), ('McGroup', 'MCommunity Group'), ('ShortCode', 'Short Code'), ('Phone', 'Phone Number'), ('Uniqname', 'Uniqname'), ('HTML', 'Static HTML')], max_length=20),
        ),
    ]
