# Generated by Django 2.2 on 2020-06-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0106_auto_20200622_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupnode',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
