# Generated by Django 2.2 on 2020-06-23 15:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0107_auto_20200622_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdomain',
            name='cost_calculated_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='arcinstance',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storageinstance',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
