# Generated by Django 2.2 on 2020-06-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0108_auto_20200623_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupdomain',
            name='cost_calculated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='backupnode',
            name='backup_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='order.BackupDomain'),
        ),
        migrations.CreateModel(
            name='ArcBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('shortcode', models.CharField(max_length=100)),
                ('arc_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcodes', to='order.ArcInstance')),
            ],
        ),
    ]
