# Generated by Django 2.2 on 2020-07-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0109_auto_20200625_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupdomain',
            old_name='total_cost',
            new_name='size',
        ),
    ]
