# Generated by Django 2.2 on 2020-07-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0111_auto_20200722_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='internal_reference_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
