# Generated by Django 3.1.2 on 2020-12-16 17:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0112_item_internal_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ticket_id', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=10)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'order_item_ticket_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('managed', models.BooleanField(default=True)),
                ('os', models.CharField(max_length=100)),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('disk_space', models.CharField(max_length=100)),
                ('regulated_data', models.BooleanField(default=False)),
                ('non_regulated_data', models.BooleanField(default=False)),
                ('replicated', models.BooleanField(default=True)),
                ('firewall', models.CharField(max_length=100)),
                ('backup', models.BooleanField(default=False)),
                ('support_email', models.CharField(max_length=100)),
                ('support_phone', models.CharField(max_length=100)),
                ('backup_time', models.TimeField(verbose_name='Daily Backup Time')),
                ('patch_time', models.TimeField(verbose_name='Daily Backup Time')),
                ('patch_day', models.CharField(max_length=8)),
                ('reboot_time', models.TimeField(verbose_name='Daily Backup Time')),
                ('reboot_day', models.CharField(max_length=8)),
                ('domain', models.CharField(max_length=100)),
                ('datacenter', models.CharField(max_length=100)),
                ('firewall_requests', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='arcinstance',
            name='thunder_x',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arcinstance',
            name='uid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='custom_form',
            field=models.CharField(blank=True, choices=[('', ''), ('TabForm', 'Base Form'), ('PhoneLocationForm', 'Phone Location'), ('EquipmentForm', 'Equipment'), ('NewLocationForm', 'New Location'), ('AddlInfoForm', 'Additional Information'), ('ReviewForm', 'Review'), ('ChartfieldForm', 'Chartfield'), ('RestrictionsForm', 'Restrictions'), ('FeaturesForm', 'Features'), ('StaticForm', 'Static Page'), ('AuthCodeForm', 'Auth Codes'), ('AuthCodeCancelForm', 'Auth Codes'), ('CMCCodeForm', 'CMC Codes'), ('ProductForm', 'Quantity Model'), ('ContactCenterForm', 'Contact Center'), ('BillingForm', 'Billing'), ('VoicemailForm', 'Voicemail'), ('DetailsCIFSForm', 'CIFS Details'), ('DetailsNFSForm', 'NFS Details'), ('AccessCIFSForm', 'CIFS Access'), ('AccessNFSForm', 'NFS Access'), ('BillingStorageForm', 'Billing'), ('BackupDetailsForm', 'Backup Details'), ('VolumeSelectionForm', 'Volume Selection'), ('SubscriptionSelForm', 'Subscription Selection'), ('DataDenForm', 'Data Den Form')], max_length=20),
        ),
        migrations.AlterField(
            model_name='storageinstance',
            name='uid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
