# Generated by Django 3.1.2 on 2020-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0113_auto_20201216_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='legacy_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='patch_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='patch_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='reboot_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='reboot_time',
            field=models.TimeField(),
        ),
    ]
