# Generated by Django 3.1.2 on 2020-12-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0022_ldapgroup_active'),
        ('order', '0114_auto_20201216_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup'),
        ),
    ]
