# Generated by Django 3.1.2 on 2020-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0116_server_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='backup_time',
            field=models.TimeField(null=True, verbose_name='Daily Backup Time'),
        ),
        migrations.AlterField(
            model_name='server',
            name='reboot_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='reboot_time',
            field=models.TimeField(null=True),
        ),
    ]
