# Generated by Django 3.1.2 on 2020-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0117_auto_20201217_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='patch_time',
            field=models.TimeField(null=True),
        ),
    ]
