# Generated by Django 3.1.2 on 2020-12-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0118_auto_20201217_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='on_call',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Business Hours'), (1, '24/7')], null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='reboot_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], null=True),
        ),
    ]
