# Generated by Django 3.1.2 on 2020-12-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0120_auto_20201218_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='disk_space',
        ),
    ]
