# Generated by Django 3.1.2 on 2021-01-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0022_ldapgroup_active'),
        ('order', '0122_auto_20210112_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='cpu',
            field=models.IntegerField(default=1, verbose_name='CPU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='in_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='database',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscauth.ldapgroup'),
        ),
        migrations.AddField(
            model_name='database',
            name='ram',
            field=models.IntegerField(default=1, verbose_name='RAM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='shortcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
