# Generated by Django 3.1.2 on 2021-01-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0123_auto_20210114_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='type_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
