# Generated by Django 3.1.2 on 2021-01-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0124_database_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MYSQL'), (1, 'MSSQL'), (2, 'Oracle')], null=True),
        ),
    ]
