# Generated by Django 3.1.2 on 2021-01-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0125_database_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='support_email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='support_phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='routing',
            field=models.JSONField(default=dict),
        ),
    ]
