# Generated by Django 3.1.2 on 2021-01-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0126_auto_20210115_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='type_name',
        ),
    ]
