# Generated by Django 3.1.5 on 2021-03-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
        ('order', '0128_auto_20210305_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='database',
            name='ram',
        ),
        migrations.AddField(
            model_name='database',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.server'),
        ),
        migrations.AddField(
            model_name='database',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='version',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent.code': 'DATABASE_VERSION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.choice'),
        ),
    ]
