# Generated by Django 3.1.5 on 2021-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
        ('order', '0130_auto_20210313_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='non_regulated_data',
        ),
        migrations.AddField(
            model_name='server',
            name='non_regulated_data',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'NON_REGULATED_SENSITIVE_DATA'}, to='project.Choice'),
        ),
        migrations.AlterField(
            model_name='server',
            name='regulated_data',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__code': 'REGULATED_SENSITIVE_DATA'}, related_name='regulated', to='project.Choice'),
        ),
    ]
