# Generated by Django 3.1.5 on 2021-03-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
        ('order', '0131_auto_20210313_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='purpose',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='database',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'DATABASE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='project.choice'),
        ),
        migrations.AlterField(
            model_name='database',
            name='version',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'DATABASE_VERSION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version', to='project.choice'),
        ),
    ]
