# Generated by Django 3.1.5 on 2021-03-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0132_auto_20210315_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
