# Generated by Django 3.1.5 on 2021-03-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscauth', '0022_ldapgroup_active'),
        ('order', '0133_auto_20210315_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='admin_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_group', to='oscauth.ldapgroup'),
        ),
    ]
