# Generated by Django 3.1.5 on 2021-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
        ('order', '0134_server_admin_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='version',
        ),
        migrations.RemoveField(
            model_name='server',
            name='backup_time',
        ),
        migrations.AddField(
            model_name='server',
            name='backup_time',
            field=models.ManyToManyField(limit_choices_to={'parent__code': 'SERVER_BACKUP_TIME'}, null=True, related_name='backup_time', to='project.Choice'),
        ),
    ]
