# Generated by Django 3.1.5 on 2021-03-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
        ('order', '0135_auto_20210318_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='backup_time',
        ),
        migrations.AddField(
            model_name='server',
            name='backup_time',
            field=models.ForeignKey(limit_choices_to={'parent__code': 'SERVER_BACKUP_TIME'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_time', to='project.choice'),
        ),
    ]
