# Generated by Django 3.1.5 on 2021-03-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
        ('order', '0136_auto_20210318_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='patch_time',
        ),
        migrations.AddField(
            model_name='server',
            name='patch_time',
            field=models.ForeignKey(limit_choices_to={'parent__code': 'SERVER_PATCH_TIME'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patch_time', to='project.choice'),
        ),
        migrations.RemoveField(
            model_name='server',
            name='reboot_time',
        ),
        migrations.AddField(
            model_name='server',
            name='reboot_time',
            field=models.ForeignKey(limit_choices_to={'parent__code': 'SERVER_REBOOT_TIME'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reboot_time', to='project.choice'),
        ),
    ]
