# Generated by Django 3.1.5 on 2021-04-13 16:24

from django.db import migrations, models
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0138_auto_20210405_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='server',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='server',
            name='public_facing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='arguments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='server',
            name='shortcode',
            field=project.models.ShortCodeField(help_text='Six digit shortcode for billing purposes.', max_length=6),
        ),
        migrations.AlterField(
            model_name='step',
            name='custom_form',
            field=models.CharField(blank=True, choices=[('', ''), ('TabForm', 'Base Form'), ('PhoneLocationForm', 'Phone Location'), ('EquipmentForm', 'Equipment'), ('NewLocationForm', 'New Location'), ('AddlInfoForm', 'Additional Information'), ('ReviewForm', 'Review'), ('ChartfieldForm', 'Chartfield'), ('RestrictionsForm', 'Restrictions'), ('FeaturesForm', 'Features'), ('StaticForm', 'Static Page'), ('AuthCodeForm', 'Auth Codes'), ('AuthCodeCancelForm', 'Auth Codes'), ('CMCCodeForm', 'CMC Codes'), ('ProductForm', 'Quantity Model'), ('ContactCenterForm', 'Contact Center'), ('BillingForm', 'Billing'), ('VoicemailForm', 'Voicemail'), ('DetailsCIFSForm', 'CIFS Details'), ('DetailsNFSForm', 'NFS Details'), ('AccessCIFSForm', 'CIFS Access'), ('AccessNFSForm', 'NFS Access'), ('BillingStorageForm', 'Billing'), ('BackupDetailsForm', 'Backup Details'), ('VolumeSelectionForm', 'Volume Selection'), ('SubscriptionSelForm', 'Subscription Selection'), ('DatabaseTypeForm', 'Database Type'), ('DatabaseConfigForm', 'Database Configuration'), ('ServerInfoForm', 'Server Info'), ('ServerSupportForm', 'Server Support'), ('ServerSpecForm', 'Server Specification'), ('ServerDataForm', 'Server Data Sensitivity'), ('DataDenForm', 'Data Den Form')], max_length=20),
        ),
    ]
