# Generated by Django 3.1.5 on 2021-04-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
        ('order', '0139_auto_20210413_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='backup_time',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'SERVER_BACKUP_TIME'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_time', to='project.choice'),
        ),
        migrations.AlterField(
            model_name='server',
            name='patch_time',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'SERVER_PATCH_TIME'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patch_time', to='project.choice'),
        ),
        migrations.AlterField(
            model_name='server',
            name='reboot_time',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'SERVER_REBOOT_TIME'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reboot_time', to='project.choice'),
        ),
    ]
