# Generated by Django 3.1.5 on 2021-04-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
        ('order', '0141_auto_20210413_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code__in': ['SERVER_UNMANAGED_OS', 'SERVER_MANAGED_OS']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='os', to='project.choice'),
        ),
    ]
