# Generated by Django 3.1.5 on 2021-04-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_choice_choicetag'),
        ('order', '0142_auto_20210413_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='on_call',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Business Hours'), (1, '24/7')], null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code__in': ['SERVER_UNMANAGED_OS', 'LINUX', 'WINDOWS']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='os', to='project.choice'),
        ),
        migrations.AlterField(
            model_name='server',
            name='patch_day',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'SERVER_PATCH_DATE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patch_day', to='project.choice'),
        ),
        migrations.AlterField(
            model_name='server',
            name='reboot_day',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'SERVER_REBOOT_DATE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reboot_day', to='project.choice'),
        ),
    ]
