# Generated by Django 3.1.5 on 2021-05-23 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0143_auto_20210430_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('', ''), ('Radio', 'Radio'), ('ST', 'String'), ('Select', 'Select'), ('List', 'List'), ('NU', 'Number'), ('Chart', 'Chartcom'), ('Label', 'Label'), ('Checkbox', 'Checkbox'), ('McGroup', 'MCommunity Group'), ('MyGroups', 'Users MCommunity Group'), ('ShortCode', 'Short Code'), ('Phone', 'Phone Number'), ('Uniqname', 'Uniqname'), ('HTML', 'Static HTML'), ('EmailField', 'Email')], max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
