# Generated by Django 3.2.4 on 2021-07-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0144_auto_20210523_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='database_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__code': 'DATABASE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_type', to='project.choice'),
        ),
    ]
