# Generated by Django 3.2.4 on 2021-07-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0145_server_database_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcinstance',
            name='research_commputing_package',
            field=models.BooleanField(default=False),
        ),
    ]
