# Generated by Django 3.2.4 on 2021-07-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0146_arcinstance_research_commputing_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcinstance',
            old_name='research_commputing_package',
            new_name='research_computing_package',
        ),
    ]
