# Generated by Django 3.2.4 on 2021-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0147_rename_research_commputing_package_arcinstance_research_computing_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcinstance',
            name='amount_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
